### ISSUE TITLE
Implement safety measures for the Kyma background delete

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1066]
### Description

Lifecycle Manager should be proofed against K8S background delete mode - this refers mainly to Kyma CR but other resources may also be affected.

In particular - we need to make sure that Manifest CRs are removed before Kyma CR is gone, this would require setting up an additional finalizer on Kyma CR

### Reasons

We want to avoid potential issues related to not using foreground delete mode in the Modularization setup.

### Acceptance Criteria

- Describe the **KCP Kyma CR** deletion
  - Given an **SKR Cluster**
    - And a **KCP Kyma CR** is created on the **KCP Cluster**
    - And a related **Manifest CR** is created on the **KCP Cluster**
  - When the **Kyma CR** is deleted using background mode
    - Then the **Manifest CR** is removed before **Kyma CR** is gone

**Comment by ruanxin** [comment]
# solution:
during kyma creation, add a finalizer, this finalizer should be only removed when:
1. it's under delete with DeletionTimestamp not zero
2. all related Manifest CR get deleted

**Comment by nesmabadr** [comment]
The API server deletes the dependents after deleting the owner; in this case the Manifest always gets deleted after Kyma CR. So the solution would be:

- During kyma creation, add a finalizer
- If the Kyma is under deletion and the related Manifests are deleted, remove the finalizer, otherwise delete the related manifests first
