### ISSUE TITLE
Revisit ServiceAccount privileges for the KLM

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1415]
### Description

Right now KLM has an elevated set of privileges to run in the K8S cluster. It should be reduced to the minimum necessary for it to operate correctly.

### Reasons

We want to keep the KCP cluster secure in case the KLM pod is compromised.

### Acceptance Criteria

- [x] KLM is running with a minimal set of privileges
  - [x] remove unnecessary verbs/resources for the KLM ClusterRole
- [x] Align with the SRE team on the requirements and expectations
- [ ] Introduce a e2e verification for plain checking minimal required RBAC privileges

**Comment by gczuczy** [comment]
Could you please revise whether do you actually need a `ClusterRole` with a `ClusterRoleBinding`? This setup gives the rules to the complete cluster, not restricted to any namespaces, at frist this seems a bit excessive. It would be much better, if you could use a namespaced RBAC for the serviceaccount, only giving permissions where it is actually needed.

**Comment by nesmabadr** [comment]
We need a ClusterRoleBinding for the CRDs as well as the gateways. The rest of the resources can be accessible via namespaced RoleBindings. 
But, we still need them to be Clusterroles because that's how the kubebuilder marker generates them and it should be generic enough for profiles other than the control-plane.
