### ISSUE TITLE
Create release guide for LM and Watcher

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1470]
## Description
Have a release guide document to describe each necessary step to release LM and Watcher components.
The goal is for each developer, who follows this guide can release LM or Wather component to landscape without questions.

Things to concern:
- how to do GitHub release: if git tag required, how to create release PR...
- how to release on Internal repo.
- troubleshooting section to collect unhappy path scenarios, can be empty in the first version.

## AC
- [x] release guide documented in internal team wiki

**Comment by c-pius** [comment]
See "Release Process" in internal wiki.

**Comment by c-pius** [comment]
Re. promotion to stage, I confirmed the following with SRE

- for promotion to stage, a semantic version MUST be provided (it is NOT possible to provide a commit hash)
- the provided semver MUST be a [version core](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) (`major.minor.patch`)
- it MUST be a version core (MAJOR.MINOR.PATCH), suffixes like pre-releases are not allowed

So for our canary verification process, we have two options:

**1.** we pile up all solved tickets until the end of the sprint (sprint review) in canary verification, create the release and promote it to stage (Tuesdays). Then we would have 3 days to verify the changes before they get promoted to further to prod
**2.** for each solved ticket that needs verification, we create a release, promote it to stage and verify it directly. On the following Monday, the changes would then be further promoted to prod.

Major problem with **1.**:  Goes against continuous integration. It may be troublesome to verify all changes at once since they may interfere with each other. (a bit of a mitigation may be to test the single changes more thoroughly on dev before a final overall test on stage)
Major problem with **2.**: We don't have an explicit release decision for the sprint. Each ticket is an entity that may be promoted all the way to prod individually.

**Comment by c-pius** [comment]
Updated version in "Release Process" in internal wiki.
