### ISSUE TITLE
Investigate start up delay of KLM

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1836]
### Description

When starting KLM, we can see a delay between the Pod running, and KLM actually picking up work (starting the reconciliation). We need to investigate the reason for this delay and if we can prevented.

### To Reproduce (observable on local deployment as well as in KCPs):

Get a new Pod of KLM created. Observe that directly after start up, we can see log entries like the ones below (starting servers, trying to acquire leader lease, checking stored versions, ...). However, it then sits there for about 3 minutes not doing anything. After about 2-3 mins, we then see reconcilation logs and things happening on the clusters.

One hint to look at is the acquisition of the leader lease. We can see a log that it is attempting to acquire the lease. The confirmation that it got the lease only comes in about 2-3 mins later.

```sh
kubectl logs deploy/klm-controller-manager -n kcp-system
{"level":"INFO","date":"2024-09-06T07:01:01.476464588Z","logger":"setup","caller":"cmd/main.go:104","msg":"starting Lifecycle-Manager version: from_dockerfile","context":{}}
{"level":"INFO","date":"2024-09-06T07:01:01.675367088Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:186","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","context":{"GVK":"operator.kyma-project.io/v1beta2, Kind=ModuleTemplate"}}
{"level":"INFO","date":"2024-09-06T07:01:01.675943505Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:202","msg":"Registering a validating webhook","context":{"GVK":"operator.kyma-project.io/v1beta2, Kind=ModuleTemplate","path":"/validate-operator-kyma-project-io-v1beta2-moduletemplate"}}
{"level":"INFO","date":"2024-09-06T07:01:01.677310963Z","logger":"controller-runtime.webhook","caller":"webhook/server.go:183","msg":"Registering webhook","context":{"path":"/validate-operator-kyma-project-io-v1beta2-moduletemplate"}}
{"level":"INFO","date":"2024-09-06T07:01:01.67917138Z","logger":"controller-runtime.metrics","caller":"server/server.go:208","msg":"Starting metrics server","context":{}}
{"level":"INFO","date":"2024-09-06T07:01:01.679687047Z","logger":"controller-runtime.metrics","caller":"server/server.go:247","msg":"Serving metrics server","context":{"bindAddress":":8080","secure":false}}
{"level":"INFO","date":"2024-09-06T07:01:01.68032863Z","caller":"manager/server.go:83","msg":"starting server","context":{"name":"health probe","addr":"[::]:8081"}}
{"level":"INFO","date":"2024-09-06T07:01:01.681180005Z","logger":"controller-runtime.webhook","caller":"webhook/server.go:191","msg":"Starting webhook server","context":{}}
{"level":"INFO","date":"2024-09-06T07:01:01.684769838Z","logger":"controller-runtime.certwatcher","caller":"certwatcher/certwatcher.go:161","msg":"Updated current TLS certificate","context":{}}
{"level":"INFO","date":"2024-09-06T07:01:01.685888172Z","logger":"controller-runtime.webhook","caller":"webhook/server.go:242","msg":"Serving webhook server","context":{"host":"","port":9443}}
I0906 07:01:01.687028       1 leaderelection.go:254] attempting to acquire leader lease kcp-system/893110f7.kyma-project.io...
{"level":"LEVEL(-2)","date":"2024-09-06T07:01:01.689037588Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:21","msg":"Handling dropping stored versions for, map[Kyma:v1beta1 Manifest:v1beta1 ModuleTemplate:v1beta1 Watcher:v1beta1]","context":{}}
{"level":"INFO","date":"2024-09-06T07:01:01.692686922Z","logger":"controller-runtime.certwatcher","caller":"certwatcher/certwatcher.go:115","msg":"Starting certificate watcher","context":{}}
{"level":"LEVEL(-2)","date":"2024-09-06T07:01:01.693148797Z","logger":"setup","caller":"cmd/main.go:255","msg":"scheduled job for cleaning up metrics","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.169369714Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:33","msg":"Checking the storedVersions for Manifest crd","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.169440755Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:42","msg":"The new storedVersions are [v1beta2]","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.18142938Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:33","msg":"Checking the storedVersions for ModuleTemplate crd","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.18145963Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:42","msg":"The new storedVersions are [v1beta2]","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.186495547Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:33","msg":"Checking the storedVersions for Watcher crd","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.186523839Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:42","msg":"The new storedVersions are [v1beta2]","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.194104589Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:33","msg":"Checking the storedVersions for Kyma crd","context":{}}
{"level":"DEBUG","date":"2024-09-06T07:01:02.194134672Z","logger":"storage-version-migration","caller":"crd/storage_version_dropper.go:42","msg":"The new storedVersions are [v1beta2]","context":{}}
```

2-3 mins pause

```sh
I0906 07:04:05.144952       1 leaderelection.go:268] successfully acquired lease kcp-system/893110f7.kyma-project.io
{"level":"INFO","date":"2024-09-06T07:04:05.149399673Z","caller":"event/skr_events_listener.go:66","msg":"Listener is starting up...","context":{"Module":"Listener","Addr":":8082","ApiPath":"/v1/lifecycle-manager/event"}}
{"level":"INFO","date":"2024-09-06T07:04:05.149960173Z","caller":"event/skr_events_listener.go:66","msg":"Listener is starting up...","context":{"Module":"Listener","Addr":":8083","ApiPath":"/v1/module-manager/event"}}
{"level":"DEBUG","date":"2024-09-06T07:04:05.146138048Z","logger":"events","caller":"recorder/recorder.go:104","msg":"klm-controller-manager-6dd847c9cb-vwbvz_4e420c6d-2632-4927-8440-7b9a515f76e5 became leader","context":{"type":"Normal","object":{"kind":"Lease","namespace":"kcp-system","name":"893110f7.kyma-project.io","uid":"5de744b0-be1d-44d8-9084-d850f45d3379","apiVersion":"coordination.k8s.io/v1","resourceVersion":"17187"},"reason":"LeaderElection"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155427173Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"watcher","controllerGroup":"operator.kyma-project.io","controllerKind":"Watcher","source":"kind source: *v1beta2.Watcher"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155514173Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"mandatory-module-installation","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"kind source: *v1beta2.Kyma"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155575965Z","caller":"controller/controller.go:183","msg":"Starting Controller","context":{"controller":"watcher","controllerGroup":"operator.kyma-project.io","controllerKind":"Watcher"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155598715Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"mandatory-module-installation","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"kind source: *v1beta2.ModuleTemplate"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155634132Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"mandatory-module-installation","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"kind source: *v1.Secret"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155653507Z","caller":"controller/controller.go:183","msg":"Starting Controller","context":{"controller":"mandatory-module-installation","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155961798Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"manifest","controllerGroup":"operator.kyma-project.io","controllerKind":"Manifest","source":"kind source: *v1beta2.Manifest"}}
{"level":"INFO","date":"2024-09-06T07:04:05.155998882Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"manifest","controllerGroup":"operator.kyma-project.io","controllerKind":"Manifest","source":"kind source: *v1.Secret"}}
{"level":"INFO","date":"2024-09-06T07:04:05.157293882Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"manifest","controllerGroup":"operator.kyma-project.io","controllerKind":"Manifest","source":"channel source: 0xc001390620"}}
{"level":"INFO","date":"2024-09-06T07:04:05.157430257Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"kyma","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"kind source: *v1beta2.Kyma"}}
{"level":"INFO","date":"2024-09-06T07:04:05.157487882Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"kyma","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"kind source: *v1beta2.ModuleTemplate"}}
{"level":"INFO","date":"2024-09-06T07:04:05.157508507Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"kyma","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"kind source: *v1.Secret"}}
{"level":"INFO","date":"2024-09-06T07:04:05.157526673Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"kyma","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"kind source: *v1beta2.Manifest"}}
{"level":"INFO","date":"2024-09-06T07:04:05.157535007Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"kyma","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","source":"channel source: 0xc001390540"}}
{"level":"INFO","date":"2024-09-06T07:04:05.159199965Z","caller":"controller/controller.go:175","msg":"Starting EventSource","context":{"controller":"mandatory-module-deletion","controllerGroup":"operator.kyma-project.io","controllerKind":"ModuleTemplate","source":"kind source: *v1beta2.ModuleTemplate"}}
...
```

### Reasons

Speed up local testing, avoid disruptions in production (when rolling out changes like with the certs).

### Acceptance Criteria

- [x] Found reason for the start up delay
- [x] Suggested or implemented a fix

**Comment by c-pius** [comment]
Also noticed that this delay only seems to happen when there is an existing KLM pod which is replaced by a new one. In a fresh cluster with fresh KLM deployment, the delay does not seem to happen.

**Comment by medmes** [comment]
# Proposal

As stated in the Ticket, We have identified a delay in the startup of the **Kyma Lifecycle Manager (KLM)** when a new KLM pod replaces an existing one. This delay, approximately 2-3 minutes, occurs before the reconciliation process begins. Upon investigation, it appears that the delay is primarily due to the leader election process.

Leader election briefly is a fundamental concept in distributed systems where multiple instances of a service or application must coordinate to ensure that only one instance (the leader) performs certain critical or conflicting tasks. This ensures consistency and prevents race conditions.
In Kubernetes, leader election is typically used for controllers to ensure that only one instance of the controller is actively reconciling resources at any given time.

## Problem Statement
### Observed Delay:
When a new KLM pod starts, it attempts to acquire the leader lease. This process involves waiting for the lease duration and retrying if the lease is not immediately available. The observed delay of 2-3 minutes occurs because the new pod must wait for the lease to expire or be released by the previous leader.

### Current Configuration:
It's clear that the current leader election settings in the KLM codebase are:
**LeaseDuration**: 180 seconds (3 minutes)
**RenewDeadline**: 120 seconds (2 minutes)
These values are quite high, which explains the delay. The new pod must wait for these durations before it can take over as the leader.

## Reason/Cause
High Lease Duration and Renew Deadline:
The high values for LeaseDuration and RenewDeadline are intended to ensure stability and prevent frequent leader changes. However, they also cause significant delays in the leader election process, particularly when a new pod replaces an existing one.

### Impact on Reconciliation
The delay in acquiring the leader lease directly impacts the start of the reconciliation process, leading to a lag before the new pod can begin processing.

## Proposed Solution
Adjust Leader Election Timing Parameters:
To address the startup delay, we propose adjusting the leader election timing parameters to more typical values that balance quick failover with system stability. Specifically:

**LeaseDuration**: 20 seconds
**RenewDeadline**: 15 seconds
**RetryPeriod**: 3 seconds

### Justification
**LeaseDuration**: A shorter LeaseDuration reduces the time to detect a failed leader, facilitating quicker failover.
**RenewDeadline**: A shorter RenewDeadline ensures that the current leader renews the lease promptly, reducing the risk of unnecessary leader changes.
**RetryPeriod**: A moderate RetryPeriod ensures frequent retries without overwhelming the API server.

### Kubernetes Controller Runtime Documentation:
The [controller-runtime documentation](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/leaderelection) provides guidance on configuring leader election with typical values for LeaseDuration (15-30 seconds), RenewDeadline (10-20 seconds), and RetryPeriod (2-5 seconds). These values are designed to balance reliability and performance.

### Empirical Data:
Historical data shows that the current settings lead to significant delays during the leader election process. By reducing these values, we can expect to see a reduction in the reconciliation start time from 2-3 minutes to under 30 seconds, improving overall system responsiveness.

### Suggested Implementation
Here is the updated setupManager function with the proposed leader election values:
```

       DefaultLeaderElectionLeaseDuration                                  = 20 * time.Second
       DefaultLeaderElectionRenewDeadline                                  = 15 * time.Second
       DefaultLeaderElectionRetryPeriod                                    = 3 * time.Second


```
[internal/pkg/flags/flags.go:64](https://github.com/kyma-project/lifecycle-manager/blob/388d6026573a35a307f8aff91d5debe0ebcd379e/internal/pkg/flags/flags.go#L64)

### PR: 
https://github.com/kyma-project/lifecycle-manager/pull/2146

## Functional Test
ou can create a functional test. This test should:

1. Deploy the KLM with the updated leader election settings.
2. Monitor the startup time and the time it takes for the reconciliation process to begin.
3. Verify that the delay is within acceptable limits (e.g., less than 30 seconds).

**Comment by c-pius** [comment]
Can confirm that this works on a local clusters. Not a matter expert, but the [defaults from kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) are indeed closer to what Mo suggests:

- leader-elect-lease-duration duration: 15s
- leader-elect-renew-deadline duration: 10s
- leader-elect-retry-period duration: 2s

Is anyone aware of a reason why such high values have been chosen instead?

**Comment by Tomasz-Smelcerz-SAP** [comment]
@c-pius Yes, It was raised on purpose: https://github.com/kyma-project/lifecycle-manager/pull/1443

We did that so that Lifecycle-Manager can survive etcd outages. I think it's fine to reduce the numbers, but I would try more conservative approach: Let's reduce it by 30% (or something like that) and observe the Lifecycle-Manager pod stability in the environments.

**Comment by medmes** [comment]
@Tomasz-Smelcerz-SAP  and @c-pius  In this case , I prefer to tackle the **etcd configuration setup** to handle the HA for example or Resource Management such as Resource Requests and Limits  on etc pods rather than relying on the KLM.

**Comment by c-pius** [comment]
Summary as discussed in 2024-12-27 daily. The main thing that bothers us is the delay in local testing. This we can configure separately. For the live production environments, we introduced the long intervals for a reason (the etcd outages). This is right now more important to us than the delays on restarts of lifecycle manager. Conclusion: we reduce the intervals for local testing, we keep the current intervals in the live production environments.
