### ISSUE TITLE
Create Non-Namespaced CRD when trying to apply the Kyma CRD during SKR Installation so that only one Kyma can be created in a managed SKR

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/lifecycle-manager#184]
As per https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition it is possible to create namespaced CustomResources when the `spec.scope` field is set correctly. This causes a CR to be applied Cluster-Wide. For dual-cluster mode, we need to apply our CRD by default as Namespaced in KCP (as this allows us to maintain N Kyma CRs for N Clusters). However, in SKR the managed Cluster itself is not able to have multiple Kymas. Thus it would make sense to have the Kyma non-namespaced during the Sync. 

AC:

- [ ] This can be achieved in the installation logic in https://github.com/kyma-project/lifecycle-manager/blob/969fde1656abec7f9c626eabb81da2e8540b13ba/operator/pkg/remote/kyma_synchronization_context.go#L156-L158 by also overriding the scope field. 
- [ ] In addition the Fetch Logic in https://github.com/kyma-project/lifecycle-manager/blob/969fde1656abec7f9c626eabb81da2e8540b13ba/operator/pkg/remote/kyma_synchronization_context.go#L183 has to be adjusted to fetch a globally scoped Kyma from the Runtime
- [ ] Tests have to be adjusted accordingly

Requirement is especially useful for busola as it can then display the Kyma in SKR much easier.

**Comment by valentinvieriu** [comment]
I would not say it's a hard requirement, but the Resource Creation will show off in every Namespace.
I would actually say that this is misleading in a way, the user thinks that he can create CR instances in it's own Namespace.

**Comment by jakobmoellersap** [comment]
What do you mean with `show off in every Namespace`. What exactly is misleading? They would not be able to create multiple CRs of Kyma in SKR if its globally scoped like suggested in the ticket.

**Comment by ruanxin** [comment]
IMO, If the main purpose for cluster-scoped Kyma is not misleading users to create Kyma CR in different namespace, I think it's a miss use for cluster-scoped resource. To me, to decide if a CR should be cluster-scoped or not should come from the direction how is this resource being used or managed. For example, `PV` designed as cluster-scoped because it can be used for Pod from different namespace. `ClusterRole` is used for managing permission for resources across clusters.

Our Kyma CR is only designed to manage all Kyma related module CRs, which will be deployed under same namespace I believe, e.g: kyma-system. so I think make it cluster-scoped is not follow this concept.

Back to the point that users can create Kyma CR under different namespace, although we can't prevent it, but we can restrict our lifecycle manager only operate Kyma CR under defined namespace, simply ignore all other CR created in different namespaces. And this role can be mentioned in Kyma document to guide users how to treat Kyma CR properly.

**Comment by jakobmoellersap** [comment]
I disagree in this scenario. Imo the Kyma CR has only one purpose, which is managing the installation of resources of a Kyma Cluster. In SKR there is never a scenario where you would be able to run more than one Kyma CR. The entire setup is managed so I think there is no point in namespacing it.

**Comment by jakobmoellersap** [comment]
This feature request has been rejected by @kyma-project/jellyfish 

There are x reasons:

- When going for this, we remove the capability in the future of using an SKR as a control-plane (we call this concept "Kymaception" as it uses a Kyma CR in local mode to spin up its own module requirements
- It will be confusing for maintainers and users alike to have some clusters with non-namespaced Kyma and some with namespaced Kyma (control-plane)
- It is maintenance effort in managing CRD migration and there are certain scenarios during migration of non-namespaced CRDs that have to be handled differently in regards to RBAC handling

Thus we are closing this issue
