### ISSUE TITLE
Kyma Modules State not updated when the remote cluster is unreachable

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#2024]
### Description

When the remote cluster is removed or unreachable, the kyma modules state in the Kyma.Status remain Ready, although it should be in an Error state. 

There are several kymas which have this issue on DEV, for example: 926fb10a-925d-4c55-863d-a8a2da2ffb56.

### Acceptance Criteria
- [ ] Status should be set to error if the cluster is not reachable
- [ ] Introduce E2E test for this scenario: https://github.com/kyma-project/lifecycle-manager/blob/2342670c9be72df6b33c4cd6ce0d12ccbb65b371/tests/e2e/deprovision_test.go#L78

### Steps to reproduce

- Delete the remote cluster
- check the state of any enabled module in the Kyma.Status, it is in Ready state.

### Environment Type

Managed

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
modulectl Version: x.y.z
If used - k3d/k3s/minikube versions

**Comment by c-pius** [comment]
Can verify that this worked on DEV for the mentioned cluster. For STAGE, we don't have a existing Kyma that had this issue. Provoking this error may be possible, but even if we change the kubeconfig secret to point to a non-existing host, I think we would also need to restart KLM because the endpoint is cached. Could we ask SRE to temporarily shutdown the whole SKR cluster?
