### ISSUE TITLE
Set up monitoring for Kyma sync status

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#380]
**Description:**
Monitoring and metrics should be set up to reflect the sync status of Kyma resources that the Lifecycle Manager manages. This will provide an easily accessible overlook of the overall state of the Kyma Control Plane.

Alert rules will be set up as the follow-up ticket.

**Acceptance Criteria:**
- [x] Lifecycle Manager exposes metrics regarding the number of Kyma resources (gauge type)
- [x] Lifecycle Manager exposes metrics regarding the Kyma sync statuses (gauge type)
- [x] Lifecycle Manager exposes metrics representing how many Kyma CRs are in Error state and for how long - it would be nice to see which Kyma CRs are in error state for longer than X hours/days (grafana queries can provide the solution)
- [x] Metrics included in [the Grafana dashboard for the Lifecycle Manager](https://github.com/kyma-project/lifecycle-manager/tree/main/config/grafana) (propose the visualization)

**Comment by ebensom** [comment]
The lifecycle-manager should expose for each Kyma CR (unique labels `kyma_name`, `instance_id`, and possibly `shoot` in all exposed metrics):

- The current value `.status.state` field. It could be exposed as a gauge mapping string states to numeric values, or reflecting it as boolean  0 or 1 metric values, where the state is a label, e.g. 
    ```
    lifecycle_mgr_kyma_state{kyma_name="xxxx", instance_id="yyyyy", state="Ready"} = 1 
    lifecycle_mgr_kyma_state{kyma_name="xxxx", instance_id="yyyyy", state="Progressing"} = 0
    lifecycle_mgr_kyma_state{kyma_name="xxxx", instance_id="yyyyy", state="Error"} = 0
    ```
- The current value of `.status.modules[*].state` fields for all modules (as gauge, or similarly as described above)

With the exposed metrics, we should be able to cover, and get notified about 4 scenarios:

1. When lifecycle-manager or module-manager fails to reconcile a change (during module enablement, or module manifest version update) of a module operator on the runtime
2. When lifecycle-manager or module-manager fails to properly delete Kyma module during module deactivation.
3. When lifecycle-manager or module-manager fails to properly delete Kyma module(s) during Kyma deletion (could also be triggered by KEB during deprovisioning) 
4. When module operator fails to reconcile the module resources locally on the runtime (e.g. because of customer caused issue).
    - If the local module reconciliation statuses are watched and somehow synced back to the central (KCP) Kyma CR, it could be reflected in `.status.modules[*].state` fields, and the existing monitoring and alerting based on these metrics already apply
    - Otherwise the local operators could expose reconciliation status in a common, standard way, and the runtime monitoring agent would scrape the operators and remote-write such metrics to central monitoring.

**Comment by Tomasz-Smelcerz-SAP** [comment]
@ebensom Considering the metrics you described, will it be possible to derive from them some statistics that allow to answer our other ACs:
- How many Kymas are there in total
- How many Kymas are currently in the given state (Error/Processing/Ready)
- A way to tell how long the Kyma is in `Error` state, sorted from the "longest". For example: Kyma1: 2days, Kyma2: 18hours, Kyma3: 4Hours, Kyma4: 20minutes, etc...

**Comment by lindnerby** [comment]
@ebensom Do you think the increased cardinality by labels like `kyma_name` or `instance_id` is ok?
Does the VMA already provide labelling on the fly for `shoot` for example?
@Tomasz-Smelcerz-SAP With these metrics we should be ok yes. All the querying will be done on consumer side then (e.g. with PromQL)

**Comment by ebensom** [comment]
> @ebensom Do you think the increased cardinality by labels like `kyma_name` or `instance_id` is ok? Does the VMA already provide labelling on the fly for `shoot` for example? @Tomasz-Smelcerz-SAP With these metrics we should be ok yes. All the querying and aggregating can be done on consumer side then (e.g. with PromQL)

Yes, completely OK, we are talking about time series cardinality in the order of thousands magnitude with zero expected churn-rate throughout the lifetime of the runtimes. FYI for comparison currently the central monitoring handles timeseries in the order of tens millions.
shoot label is not mandatory if kyma_name and istance_id is set, whoever we discussed with @lindnerby on PM that it's possible to extract it from the domain metadata.

**Comment by ruanxin** [comment]
@lindnerby, regarding the dashboard cleanup, please also remove module manager related panel:

- Module Manager Memory
- Module Manager CPU usage
- Module Manager Kube API Request Rate

**Comment by ebensom** [comment]
@lindnerby @ruanxin There is a bug in current `lifecycle_manager_kyma_status` metric recording code, it exposes all states except Deleting with 0 status code. 
[This line](https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/metrics/metrics.go#L35) should be `string(desiredState)` instead.

**Comment by janmedrek** [comment]
I believe that would be the case, would need a double-check.

**Comment by lindnerby** [comment]
We introduced the two metrics `lifecycle_mgr_kyma_state` and `lifecycle_mgr_module_state` and a new dashboard for Kyma  and module status visualisation _Lifecycle Manager Kyma Status_. We will gradually add panels to this dashboard as we see fit.
