### ISSUE TITLE
Control-Loop for Force Finaliser Removal (Gardener Deprovisioning Compatibility)

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/lifecycle-manager#470]
As a cluster user on Gardener that is using Kyma as managed offering, the (gardener) shoot is managed completely by a controller sitting outside the shoot. When deciding to kill my cluster, aka delete all of its nodes and resources within, gardener waits for any finalisers to be completely removed from resources and will get stuck during deprovisioning if this cannot be guaranteed. 

Thus we want to introduce a custom controller that is able to force-remove any finalisers set after a set period after the deletionTimestamp was set in order to forcefully remove all finalisers. Since this is gardener specific, we will do this only if a feature flag is active and a label is set on the kyma resource: `purge.finalisers.kyma-project.io`. 

If set together with a flag `purge-finaliser-timeout` set to a duration (e.g. `5m`), then the control-loop should actively remove all finalisers as soon as `deletionTimestamp+purge-finalizer-timeout` is reached.

For more reference on the root cause, see https://github.com/gardener/gardener/issues/3110

AC:

- Custom Control Loop is introduced to Lifecycle Manager
- Loop is triggered based on deletionTimestamp set on Kyma and still being present after a set timeout
- Control Loop only gets started based on `enable-purge-finaliser` feature-flag as `bool`
- Control Loop timeout is controlled with `purge-finaliser-timeout` feature-flag as `time.Duration`
- Control Loop continuously removes all finalisers in remote clusters only, and will not work with control-plane clusters as its effect can destroy lifecycle manager / kyma reconciliation as well. 
- Consider the amount requests to APIServer while removing all finalizers, avoid too many parallel requests to overload APIServer.

**Comment by Tomasz-Smelcerz-SAP** [comment]
After thinking about the `Finaliser Removal` loop triggering, I think the correct approach must be discussed.
Currently, as I understand the AC, the proposal is: `control-loop should actively remove all finalisers as soon as deletionTimestamp+purge-finalizer-timeout is reached`
What if timeout is 5 minutes, but LM actually deletes the Kyma object in 1 minute? We're waiting 4 additional minutes to drop finalizers. It could have been done as soon the Kyma object is deleted.
If we can detect fast (or immediately) that Kyma is gone, I'd propose the following logic:
- drop finalizers as soon as Kyma is gone (object not found) in the control plane
- otherwise drop finalizers when the timeout is over (`deletionTimestamp+purge-finalizer-timeout`), regardless if there is a Kyma object or not.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Another thing is that the `Finalizer Removal` loop should skip the Kyma CR - it should not try to remove finalizers from them, to not interfere with the main Kyma reconcile loop.

**Comment by Tomasz-Smelcerz-SAP** [comment]
I also think this AC is questionable: "Loop is triggered based on deletionTimestamp set on Kyma and still being present after a set timeout".
Whether the Kyma is present or not after the timeout should not matter. The job of the custom control-loop is to drop finalisers from remote cluster so that the Gardener can gracefully remove the shoot. Even if all modules are deleted and Kyma is gone, there still may be some custom CRs in the cluster.
One source of such CRs are user installed objects.
Another is Kyma-related CR that wasn't removed due to a bug/error in one of the modules. The error in module uninstallation may not be obvious e.g. It may be related to some infrastructure issues.
We're now having the second (and final) chance to remove the CR and we should take that chance.

**Comment by lindnerby** [comment]
Re-opening due to testing on dev landscape is still due.
