### ISSUE TITLE
Add another state for module CR - Warning

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/lifecycle-manager#525]
**Description:**
The existing states cannot reflect situation when module components are started, but module cannot be used due to misconfiguration (e.g. missing dependencies). Usually it means that user interaction is required, but from lifecycle-manager perspective module is already properly deployed.

**Acceptance Criteria:**
- [ ] Provide another type of status for misconfiguration/user action required
- [ ] Treat the Warning state just like Ready and reconcile it in the same time periods (requeue after)
- [ ] Provide a description for that in docu

**Comment by tobiscr** [comment]
This issue is currently blocking us from checking the `btp-operator` module within the Kyma release pipeline.

Our pipeline expects that a module reache the `READY` state after 3 minutes, otherwise we have to assume that the module is broken.

Currently, BTP-operator stays endless in a Non-ready state and the pipeline is consistently failing. We are excluding `btp-operator` now from our Kyma release pipeline until this new status is available and can be considered by us.

**Comment by janmedrek** [comment]
@ruanxin I would use the `Warning` state for this case, it makes more sense to me as it is "ready" but not in the state that the user wants to, it would be good to display that information.

**Comment by kwiatekus** [comment]
@janmedrek @pbochynski we are figuring out how to combine this `Warning` state with `Deleting` state in our [case](https://github.com/kyma-project/keda-manager/issues/161):

When user decides to disable keda but scaledObjects still exists, should Keda CR progress from `Ready` via `Deleting` to `Warning` state? (with additional condition explaining the warning )?
