### ISSUE TITLE
Initial (default) module list in central Kyma resources

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/lifecycle-manager#756]
**Description**
The list of modules included in Kyma resource located in the control plane should be used only for initialization of Kyma resource in the target cluster. Once the Kyma resource in the SKR is created it is the single source of truth. The default module can be deleted by the user and the change will be processed by the lifecycle manager. 

**Reasons**
Right now lifecycle manager merges lists of modules from Kyma resources in the control plane and in the target cluster (SKR). If the module is deleted by the user but still exists in the control plane lifecycle manager will keep it. Such behavior was implemented for enabling modules centrally during modularization roll-out, but the migration process used another approach and the feature is not currently used. This feature also prevents users to disable the module that is configured centrally and can cause confusion.

This feature allows to move istio from reconciler to module without waiting for all other components migration. New clusters will get istio installed when we enable istio in the Kyma resource created by KEB.

Dev Notes:
- Function to remove/adapt [MergeModules](https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/remote/kyma_synchronization_context.go#L241)
- Should be implemented like mentioned [here](https://github.com/kyma-project/lifecycle-manager/issues/756#issuecomment-1696242909)

**Comment by ruanxin** [comment]
# Proposal

1. Use KCP Kyma `spec.modules`

This is low effort if we drop the mandatory default module concept (user can't disable mandatory module). We can use SKR  Kyma `spec.modules` as a source of truth, but this is against our design principle, we don't want users to change KCP Kyma `spec`.

2. Introduce some init data in KCP Kyma

We introduce some annotation in KCP Kyma which contains some modules that should be initialized.
```
annotations:
    "operator.kyma-project.io/init-modules": "{modules:["btp-operator", "istio"], state: init}" 
```
After Kyma provision is made, which means init modules are presented in SKR Kyma `spec.modules`, LM updates the state on the annotation, so that this init list can be ignored in the later reconciliation.
```
annotations:
    "operator.kyma-project.io/init-modules": "{modules:["btp-operator", "istio"], state: done}" 
```

With this solution, user will not influence KCP Kyma `spec`, as well as the mandatory default module concept.

**Comment by pbochynski** [comment]
The idea is to use KCP spec.modules as a template for newly created Kyma resources in SKRs. But KCP spec.modules section is not used for SKR reconciliation. The only source of truth is in the SKR spec.modules. So user can delete default module, but it doesn't change the spec in KCP. But is user deletes entire Kyma resource in SKR lifecycle manager will recreate it from the resource in KCP (so the default modules will be restored in SKR). 
The behavior will be similar to the default CR in module template. It is used only when module instance is created, but later on only content in the SKR edited by the user is used.
