### ISSUE TITLE
Custom module namespace 

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/lifecycle-manager#838]
**Description**
Currently all modules are deployed to the `kyma-system` namespace within the target clusters. It was agreed that modules could be located also in an individual namespace defined by the module. That namespace could be defined as part of the module resources and treated as a regular resource of a module.

However, there a components in the control-plane which like to know which namespaces a runtime will have where the namespaces are under control of modules/lifecycle-manager, as workloads in these namespaces potentially require special attention, for example in regards to operations. This information should be available in best case as part of a moduleTemplate, or even better as part of the Kyma CR, so that components can figure out in which namespaces modules are installed.

Also, the info could be used to create the namespace automatically by the lifecycle-manager (and not include it in the module resources) and directly label it with `operator.kyma-project.io/managed-by: lifecycle-manager` as it is done with kyma-system

Proposal:
- a module can define the namespace it will be installed into (as part of moduleTemplate)
- lifecycle-manager will take that info, create and label the namespace

Alternatively, the second point could be dropped and just the metadata can be provided as part of the moduleTemplate

**Reasons**

**Attachments**

**Comment by pbochynski** [comment]
The lifecycle manager will install CR in the namespace provided in the module template (spec.data.metadata.namespace). If you don't provide it it will be in kyma-system. If you want your module in abc-system just add abc-system you your module manifest and use abc-system for default CR. It should work already.

**Comment by ruanxin** [comment]
Hi @a-thaler ,

as @pbochynski mentioned, LM supports the namespace of module CR, you can just configure the namespace in your module CR yaml, take your telementry-manager as an example, you just need to configure  Telementry CR yaml with the namespace you want, but atm it just has [name](https://github.com/kyma-project/telemetry-manager/blob/main/config/samples/operator_v1alpha1_telemetry.yaml#L10) defined, just a remark, if you want to deploy it under `default` namespace, you still need to define it specifically, otherwise, it will overwrite with `kyma-system` namespace by LM during creation.

With this configuration, it will be persistent in module template `spec.data.metadata.namespace` during kyma create module, and then LM can deploy it into the expected namespace.

**Comment by a-thaler** [comment]
I see, so your recommendation is to re-use the namespace of the default module CR as the relevant namespace where the module will be operated in.
