### ISSUE TITLE
Support `customStateCheck` to look to another resource other than the one specified under the `.spec.data` field

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/lifecycle-manager#917]
### Description

Right now Cli expects (and LM) that the generated `moduletemplate` has a custom CR under the `spec.data` field and his CRD in the given manifest. Please, consider support for checking the state of resources that is not in the `.spec.data` field.

Maybe even checking more than one resource - for example, checking the count of replicas of two deployments that are in the manifest.

### Reasons

We are trying to [modularize the Warden](https://github.com/kyma-project/warden/issues/109). Based on the following requirements we think that we don't need the `warden-manager` (that installs the warden based on the Warden CR) and the Warden CR (that keeps the configuration of the warden):

* User can't  enable/disable module - warden is always enabled on SKR clusters
* User can't reconfigure the warden component
* User can see the status of the warden component - if it's installed or why not

Right now we can't do it, because CLI and LM expect that:

* `.spec.data` field is not empty
* `.spec.data` contains CR
* manifest contains CRD of the CR
* `.spec.customStateCheck` can be used only to create a custom mapping for a resource that is in the `.spec.data` field.

It would be really useful for every component that can't be reconfigured and because of that doesn't need a custom manager/installer.

### Acceptance Criteria

- [ ] Component doesn't need to have a custom resource to declare that its installed
- [ ] Component doesn't need to have its own manager to reconcile CR
- [ ] LM can directly deploy manifest and check its state based on the `customStateCheck`

### Feature Testing

Integration tests

### Testing approach

This feature should be fully tested because it's a separate use case and we don't have tests for it

**Comment by janmedrek** [comment]
It will be hard for us to implement such a feature and keep the performance of the KLM unaffected. It would require multiple additional watches, and enabling that per module will only multiply the magnitude of the problem.

For now, we have lifted the requirement for the module to have its own CR and manager, so that should simplify the overall situation.

As we discussed - we can think about alternatives, but that would require modifying the design of the Modularization framework. If you think that the default state check for the overall resource deployment status and deployment (pod) health is not enough then please feel free to reopen the issue and discuss it further.
